# Generated by Django 3.2.8 on 2021-10-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_auto_20211027_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Максимум 250 символів', max_length=250, verbose_name='Категорія'),
        ),
    ]
